name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build themes
        run: sh ./build.sh
      - name: pack themes
        run: tar -czf build.tar.gz build
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: build.tar.gz
          tag_name: latest
          prerelease: true